handler: lambdas/register-sub/register-sub.handler
name: register-sub
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/register-sub/register-sub.js
    - lambdas/register-sub/helpers/**
events:
  - http:
      method: post
      path: register
      cors: true
      authorizer:
        type: COGNITO_USER_POOLS
        authorizerId: !Ref CognitoAuthorizer
