handler: lambdas/register-sub/register-sub.handler
name: ${self:service.name}-register-sub-lambda
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/register-sub/register-sub.js
    - lambdas/register-sub/helpers/**
events:
  - http:
      method: post
      path: register
      cors: true
