handler: lambdas/register-sub/register-sub.handler
name: register-sub
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/register-sub/register-sub.js
environment:
  ES_ID: ${env:ES_ID}
  ES_SECRET: ${env:ES_SECRET}
  ES_ENDPOINT: ${env:ES_ENDPOINT}
events:
  - http:
      method: post
      path: register
      cors: true
      authorizer:
        type: COGNITO_USER_POOLS
        authorizerId: !Ref CognitoAuthorizer
