handler: lambdas/deregister-sub/deregister-sub.handler
name: deregister-sub
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/deregister-sub/deregister-sub.js
environment:
  ES_ID: ${env:ES_ID}
  ES_SECRET: ${env:ES_SECRET}
  ES_ENDPOINT: ${env:ES_ENDPOINT}
events:
  - http:
      method: post
      path: deregister
      cors: true
      authorizer:
        type: COGNITO_USER_POOLS
        authorizerId: !Ref CognitoAuthorizer
