handler: lambdas/public-key/get-public-key.handler
name: get-public-key
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/public-key/get-public-key.js
events:
  - http:
      method: get
      path: public-key
      cors: true
      authorizer:
        type: COGNITO_USER_POOLS
        authorizerId: !Ref CognitoAuthorizer
