handler: lambdas/public-key/get-public-key.handler
name: get-public-key
layers:
  - { Ref: ApiLayerLambdaLayer }
package:
  include:
    - lambdas/public-key/get-public-key.js
    - lambdas/public-key/helpers/**
events:
  - http:
      method: get
      path: public-key
      cors: true
      authorizer:
        type: COGNITO_USER_POOLS
        authorizerId: !Ref CognitoAuthorizer
      kaskadi-docs:
        description: This endpoint returns the public key used in the push-notification protocol. **For now it only returns the public key related to the Kaskadi project!**
        examples:
          - request: {}
            response:
              statusCode: 200
              headers:
                'Access-Control-Allow-Origin': '*'
              body:
                publicKey: kaskadi_push_notification_public_key
